//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Debt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtorUser
    {
        public string id { get; set; }
        public string did { get; set; }
        public string uid { get; set; }
    
        public virtual Debtor Debtor { get; set; }
        public virtual User User { get; set; }
    }
}
