//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Debt.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DebitNotes = new HashSet<DebitNote>();
            this.DebtorUsers = new HashSet<DebtorUser>();
        }

        [Required]
        public string uid { get; set; }
        [Required(ErrorMessage = "Vui lòng điền tên đăng nhập")]
        [Display(Name ="Tên đăng nhập")]
        public string username { get; set; }
        [Required(ErrorMessage = "Vui lòng điền mật khẩu")]
        [MinLength(8, ErrorMessage = "Tối thiểu 8 kí tự")]
        [Display(Name = "Mật khẩu")]
        public string password { get; set; }
        [Required(ErrorMessage = "Vui lòng điền mật khẩu lần 2")]
        [Compare("password", ErrorMessage = "Vui lòng nhập cùng một mật khẩu")]
        [Display(Name = "Nhập lại mật khẩu")]
        public string confirm_password { get; set; }
        [Required(ErrorMessage = "Vui lòng điền email")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string email { get; set; }
        public string confirm_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebitNote> DebitNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtorUser> DebtorUsers { get; set; }
    }
}
